### ISSUE TITLE
Request about the new variables

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#22] opened 2022-12-17 18:19 UTC
Could you, please, add some new options for Form variables and conditions?

Add Self here:
[https://i.imgur.com/GLUhK1C.png](https://i.imgur.com/GLUhK1C.png)
And Mounting actor here:
[https://i.imgur.com/PqRCCrA.png](https://i.imgur.com/PqRCCrA.png)

The reason I'm asking, it's to make equipment overrides more easily.
The variables functions are really powerful and handy to condition. Example you can have a condition like Form Var != 0, which means this variable has loaded a form, and use it to disable or reposition another display.

And another question about these variables, are there any plans to include some functions in the scripts to access them? I think the int and float could be very useful.

**Comment by SlavicPotato** [comment] 2022-12-21 18:12
> are there any plans to include some functions in the scripts to access them?

Yes, I planned that from the start (not sure when I'll get to it though). Form variables will be of most use here, global variables can already be used for integers/floats.

**Comment by GiraPomba** [comment] 2022-12-21 18:31
That's awesome. 
Yeah, form vars will be very useful indeed, but float and int will have their uses too. 
Globals are useful, but you need to create them in a plugin and use them in the scripts. With vars it'll be more straightforward I think.

Anyway, thanks for such cool features.

**Comment by GiraPomba** [comment] 2022-12-27 23:56
Hey. Just wanted to ask you something.
Are you amenable to add some functions to return what node is defined for the weapons in "Gear positioning"?

I want to do some dynamic stuff with an animation mod I have.

**Comment by SlavicPotato** [comment] 2022-12-31 15:00
The existing implementation already tracks which node is positioned where (for anim switching switching purposes) so it'd be simple to add, the problem is that there's currently no way to notify your plugin when a change occurs, you'd have to periodically poll it which isn't ideal. What exactly are you trying to do?

**Comment by GiraPomba** [comment] 2022-12-31 15:59
I released this [mod](https://www.nexusmods.com/skyrimspecialedition/mods/77017), mainly for Nemesis users or for someone looking for alternatives to animations. It uses DAR, conditioned with Globals that correspond to the animation selected in the MCM.
At the moment, it needs manual input, so I was trying to create something more automatic.
It could be useful with overrides as with IED you can define, for example, the Sword back node for swords, but create an override that uses the Sword (hip) instead when a two handed is equipped. In this case the animation would be still the sword at back unless the user manually changes.

Some sort of Event OnWeaponNodeChange or something would be perfect, but a function that returns the node would be enough too, then I could call it with the Event OnObjectEquipped maybe.

**Comment by GiraPomba** [comment] 2023-01-10 23:10
Thanks for looking into it.

About the lights, I was trying to create a display to place lit torches near the player with IED, but there where no lights... And now you just dropped this update lol. I will check it in-game now, thanks.

**Comment by SlavicPotato** [comment] 2023-01-10 23:37
If you want something more realistic, you'll need to make a LIGH form and possibly a mesh. Example below uses the vanilla candlelight spell mesh. 'Play sequence' needs to be checked (set sequence to mLoop) and maybe add some conditions so it turns off if candlelight/invisibility effect is active, during the day, indoors, .. and you've got a nice permanent night light.

[IED_Candlelight.zip](https://github.com/SlavicPotato/ied-dev/files/10387543/IED_Candlelight.zip)

**Comment by GiraPomba** [comment] 2023-01-11 01:04
Ahh, so that's how "Play sequence" works, it needs to be something that's in the mesh. Got it.
Btw, do I need to toggle something else in order for the lights to work? I created a display for the torch and toggled "Attach light", but it didn't work.
As for the mesh in the file you provided, the light worked only by toggling "Play sequence" with mLoop.

**Comment by SlavicPotato** [comment] 2023-01-11 01:14
A small mistake caused lights not to get attached at all, fixed in 809e75a. What you probably thought was a light was actually just the glow mesh surrounding it. I'll get new builds up in a bit.

**Comment by GiraPomba** [comment] 2023-01-11 01:18
Yeah, I figured it out haha. Thanks.

I'll try to add the candlelight animations to a torch model, a floating torch wouldn't be too bad.
Some really awesome features in this version, you are wizard..

**Comment by GiraPomba** [comment] 2023-01-11 04:11
Lights are working fine now and the script functions were just what I was looking for. Thanks...

Btw, I tried to use [this](https://www.nexusmods.com/skyrimspecialedition/mods/25865) mod to create a floating torch display, by creating the light form, with torchlightspellactorfx.nif, just as you did with the candlelight, but it didn't work as expected, as you can see in this [video](https://imgur.com/FPSV5mP). The giant torch spinning is the IED preset, the torch floating normally to the right is the same item, but placed with console commands. The spell work fine too.
There is probably something in the nif, but I can't put my finger on it.

**Comment by SlavicPotato** [comment] 2023-01-11 04:43
Spinning one is `torchlightspellactorfx.nif` , you probably want `_torchlightspellhazard.nif`, the one that's loaded from the hazard form and links to the light. Make a copy of `_Torch01`, change the model path to `magic\_torchlightspellhazard.nif` and use that. Btw NifSkope can play sequences, just load the meshes and check which one has the correct anims.

![Capture](https://user-images.githubusercontent.com/66538381/211719416-ecf8e467-79b3-4a30-b86c-a9f5acbcedd5.PNG)

**Comment by GiraPomba** [comment] 2023-01-11 12:39
Yeah, that did the trick. I guess I overlooked the plugin in xEdit and also missed the animation part in NifSkope, smh.
Thanks again.

**Comment by GiraPomba** [comment] 2023-01-15 02:51
Hey, I think you can close this issue as the original request is complete, the discussion deviated a little bit.
I could open a new one for the weapon node change stuff, but only if you're going to do that, of course.

**Comment by SlavicPotato** [comment] 2023-01-15 09:37
I think the best solution would be adding actor variables directly to the animation replacer. Not much chance that will happen with DAR, luckily there's open variant of the animation replacer in the works. The switch needs to happen in real time but with papyrus in the middle of IED and DAR, delays could be very high. Plus the globals condition in DAR isn't of much use for npcs.

**Comment by GiraPomba** [comment] 2023-01-15 10:57
Yes, you're right. The global is only useful if all NPCs use the same placement for the weapons.
I think a direct communication between IED and OAR would be best, you would set up the folders names with the animations and IED would send the info to OAR instead of using the FNIS with XPMSE. 
Or OAR could have a new condition to look for IED weapon placements, but it would also need a functionality to dynamically detect the actors to properly function with NPCs.

Just thoughts...

**Comment by SlavicPotato** [comment] 2023-01-15 11:47
Nothing complicated like that, variables like behavior graphs have would be enough. IED would set some predetermined vars based on current positioning, then you could use them in OAR conditions.

**Comment by GiraPomba** [comment] 2023-01-15 13:01
I see, thanks for the input.

**Closed** 2023-01-15 17:32 UTC
Labels: enhancement
