### ISSUE TITLE
Link actor gear placement to OAR conditions

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#33] opened 2023-03-13 15:22 UTC
Hey, we talked about this previously.
It seems like OAR will have conditions by behavior variables. 
Could you add these variables when updating actor weapon placements? I believe each actor will have their own variables, right? Thanks.

**Comment by GiraPomba** [comment] 2023-03-13 16:08
Hmm... I misunderstood what you meant earlier. I thought IED would update a variable on the actor so it could be used as a condition in OAR.
I'll see if something can be done then.

**Comment by SlavicPotato** [comment] 2023-03-13 16:20
> I thought IED would update a variable on the actor

You did understand that part right, just not the part about directly writing behavior graph variables. As far as I'm aware, those are defined in the behavior graphs beforehand and can't be trivially created at runtime, but even if that's no the case, the risk of breaking something would be too high IMO.

**Comment by GiraPomba** [comment] 2023-03-13 16:29
That makes sense. Will check with Ersh what OAR can do about this.

**Comment by GiraPomba** [comment] 2023-03-14 11:51
Hey, OAR will have an API that could have some sort of variables storage system. Maybe sonething can be done through it.

**Comment by GiraPomba** [comment] 2023-05-06 15:03
Hey, I don't know if you have been working on this, but I had this idea on how it could be implemented. 
It would involve setting graph vars on the actors, something you were against before I know, but I think It wouldn't cause any problems. 
You wouldn't have to worry about editing behavior files either, as this would be done by the user/modder and papyrus has a function to update graph vars on runtime, so it could be called from IED(the SKSE equivalent of that function). Well, if you are interested I can give more details.

**Comment by SlavicPotato** [comment] 2023-05-07 09:04
> It would involve setting graph vars on the actors, something you were against before I know, but I think It wouldn't cause any problems.

What I was getting at is that variables are intended to be used with graphs, (ab)using exclusively to pass data between two skse plugins isn't a good solution. I did some RE since then and as I suspected they're not automatically created just by invoking SetGraphVariable(type) so they'd either have to be predefined (behavior patching) or created at runtime by other means. Both options suck for this use case.

**Comment by GiraPomba** [comment] 2023-05-07 13:32
Hmm, I see.
I was thinking about editing behavior files to create the variables. With [Behavior Data Injector ](https://www.nexusmods.com/skyrimspecialedition/mods/78146) you can easily add those variables. This would on the user end.
So, IED could have some sort of config settings were user would create or import. Similar to "Placement" in "Gear nodes", with overrides or multiple configs because of the unrestricted placement.
Something like "Sword>Sword back>Variable Name(string), VariableType( int, bool, float), VariableValue"
Then IED could call the function SetAnimationVariableInt() (or bool or float) on the actor based on the configs, which then could be used in OAR 

But yeah, maybe something better could be implemented.

**Comment by SlavicPotato** [comment] 2023-08-12 16:21
I've implemented OAR conditions that can be used to read placement info from IED:

```IED_GearNodePlacementHint``` - gets a [placement hint](https://github.com/SlavicPotato/ied-dev/blob/4177d28b533c00c876f9512f91615111d17ee1e8/ImmersiveEquipmentDisplays/IED/WeaponPlacementID.h) based on where a [gear node](https://github.com/SlavicPotato/ied-dev/blob/4177d28b533c00c876f9512f91615111d17ee1e8/ImmersiveEquipmentDisplays/IED/GearNodeID.h) (first parameter) is attached and compares it to the second parameter

```IED_GearNodeParentName``` - gets the parent node name of the specified [gear node](https://github.com/SlavicPotato/ied-dev/blob/4177d28b533c00c876f9512f91615111d17ee1e8/ImmersiveEquipmentDisplays/IED/GearNodeID.h) (first parameter) and tests if it's equal to the second parameter

```SDS_IsShieldOnBackEnabled``` - checks if SDS has shield on back enabled for the actor

The hint thing is probably most practical, unless you want a different anim for a specific MOV node.. See [here](https://github.com/SlavicPotato/ied-dev/blob/4177d28b533c00c876f9512f91615111d17ee1e8/ImmersiveEquipmentDisplays/IED/NodeOverrideData.cpp#L76-L124) which [hint](https://github.com/SlavicPotato/ied-dev/blob/4177d28b533c00c876f9512f91615111d17ee1e8/ImmersiveEquipmentDisplays/IED/WeaponPlacementID.h) is assigned to which MOV. Let me know if you've got some suggestions on these assignments.

Beta built is attached to the comment, the [condition plugin](https://github.com/SlavicPotato/OpenAnimationReplacer-IEDConditionExtensions/tree/master) is separate from IED/SDS, you can build it easily enough
[ImmersiveEquipmentDisplays.zip](https://github.com/SlavicPotato/ied-dev/files/12327786/ImmersiveEquipmentDisplays.zip)
[ImmersiveEquipmentDisplays.zip](https://github.com/SlavicPotato/ied-dev/files/12327789/ImmersiveEquipmentDisplays.zip)

**Comment by GiraPomba** [comment] 2023-08-12 16:56
That's awesome, thanks a lot.
I think those conditions will be enough, but I'll test it later today and let you know.

I never built a plugin before tbh, but I'll give it a go. Shouldn't be too hard.

**Comment by SlavicPotato** [comment] 2023-08-12 18:03
It's a few short commands in powershell to install xmake and build the thing, just follow the readme..

[New build](https://github.com/SlavicPotato/ied-dev/files/12327999/ImmersiveEquipmentDisplays.zip), had to make some changes for performance reasons

**Comment by GiraPomba** [comment] 2023-08-12 18:14
I'm struggling at the Rapidcsv install, but I guess it's the C++ compiler. I'm installing it with Visual Studio now.
But it's good to know, maybe I can make a SKSE plugin in the future, who knows lol...

Does this build works with Skyrim 1.6.640 btw?

**Comment by SlavicPotato** [comment] 2023-08-12 18:20
Oh sorry I forgot to ask what you use.. That's the pre build, here's the post and I included the current oar plugin build

[Plugins.zip](https://github.com/SlavicPotato/ied-dev/files/12328030/Plugins.zip)

**Comment by GiraPomba** [comment] 2023-08-12 18:23
Thanks, I just recently installed 1.6.640, I was hesitating but it isn't that bad. 
Everything is more stable now haha.

That'll sabe me some time.

**Comment by GiraPomba** [comment] 2023-08-12 18:46
Seems to be working perfectly so far.

But how about nodes created with the Skeleton Extender? I have this mod [here](https://www.nexusmods.com/skyrimspecialedition/mods/92244) that adds new nodes, Maces on back, Swords at back hip and such..
I guess a new parameter in the Json to define the [placement hint](https://github.com/SlavicPotato/ied-dev/blob/4177d28b533c00c876f9512f91615111d17ee1e8/ImmersiveEquipmentDisplays/IED/WeaponPlacementID.h) would be enough.

**Comment by SlavicPotato** [comment] 2023-08-12 18:48
> I guess a new parameter in the Json to define the [placement hint](https://github.com/SlavicPotato/ied-dev/blob/4177d28b533c00c876f9512f91615111d17ee1e8/ImmersiveEquipmentDisplays/IED/WeaponPlacementID.h) would be enough.

Already there, `placement_id`

It's clamped to 0-8 range when read from json, I'll remove that

**Comment by SlavicPotato** [comment] 2023-08-12 18:55
[ImmersiveEquipmentDisplays.zip](https://github.com/SlavicPotato/ied-dev/files/12328087/ImmersiveEquipmentDisplays.zip)

You can assign a unique ID for your nodes now

**Comment by GiraPomba** [comment] 2023-08-12 19:01
Perfect..

Another question, does IED or SDS knows if [CGO](https://www.nexusmods.com/skyrimspecialedition/mods/33767) is installed?
I want to add dual wield animations for 2h weapons, but if it's not installed, the game considers 2h weapons equipped on both hands, so that wouldn't work very well. I don't want to create an .esp just to have a toggle to enable CGO support...

**Comment by SlavicPotato** [comment] 2023-08-12 19:02
I could add an IsPluginLoaded condition, wouldn't be foolproof but close enough I guess

**Comment by SlavicPotato** [comment] 2023-08-12 19:04
Or maybe not, iirc it has a toggle for that it's not just on by default.. Maybe it has a global variable that shows whether it's enabled?

**Comment by GiraPomba** [comment] 2023-08-12 19:06
Yeah, it adds a plugin, I think I can use a existing condition within OAR for that.

**Comment by SlavicPotato** [comment] 2023-08-12 19:14
CompareValues can be used to match a global var

**Comment by GiraPomba** [comment] 2023-08-12 19:24
Yah, that can work.
Does IED assign the same GearNodeID for two handed weapons on the left hand? 
I guess it's SDS that creates the display for the equipped weapon and IED only creates the display for the unequipped weapon on the display manager if enabled there.

**Comment by SlavicPotato** [comment] 2023-08-12 19:45
There's no left 2h gear node to speak of in the vanilla game and neither plugin really needs it.. SDS redirects the geometry onto an arbitrary node (if it detects a lh equip) after the game creates it, IED just treats lh/rh hand forms as separate pieces of gear and also attaches to an arbitrary node..

I could add it to the so called 'weapon nodes' (gear nodes is more accurate, the labeling is horrible in the code lol) list and assign a name/id to it, it would be picked up automatically if defined in extra nodes (there should already be WeaponBackLeft and WeaponBackAxeMaceLeft in the public package)

**Comment by GiraPomba** [comment] 2023-08-12 19:50
Only if you are willing to haha. I guess most users would assign the same node as the right hand weapon, so it should work fine for the animations.

**Comment by SlavicPotato** [comment] 2023-08-12 20:15
That should probably do it. 00205_2HLeft.json (included in 1.7) needs to be loaded for it to work. You can tweak anything on those nodes except ```name```, ```cme_name``` and ```mov_name```.

[ImmersiveEquipmentDisplays.zip](https://github.com/SlavicPotato/ied-dev/files/12328203/ImmersiveEquipmentDisplays.zip)

**Comment by SlavicPotato** [comment] 2023-08-12 20:15
Fair warning: I didn't test it at all lol

**Comment by GiraPomba** [comment] 2023-08-12 21:06
Lol.. nice, I'll test it and let you know.
So far it's working great. Thanks again.

You went out of the way to add the conditions, it's amazing. IED it's revolutoniary, so is OAR.
I hope you can port IED to Fallout 4 in the future. I guess the games are similar in structure, there's F4SE and CommonLib I think, maybe the skeletons are an obstacle.

**Comment by SlavicPotato** [comment] 2023-08-12 22:33
Making some nice replacer configs is thanks enough so we can finally move away from xp32 and I can stop telling people to sync up the placement configs just so their anims work on nemesis heh

**Comment by GiraPomba** [comment] 2023-08-12 23:35
Fair enough haha

**Comment by GiraPomba** [comment] 2023-08-13 02:42
I can't get them to work, probably doing something wrong. I only managed to enable the node with SDS, but it doesn't change in IED. And I think it needs a new ID to use in the OAR plugin? But it's fine if you revert the changes tho, no problem.

How to enable Two-Handed Axe/Mace btw? And how to use Two-Handed IED? I guess it was Two-Handed Extra before, but I never managed to get it working.

**Comment by GiraPomba** [comment] 2023-08-13 04:18
Oh, changing the placement in the UI works for Two-Handed (Greatswords) but not for Two-Handed Axes/Maces.

**Comment by SlavicPotato** [comment] 2023-08-13 08:25
```WeaponBackAxeMaceLeft```should be fixed. Check out their assigned ids [here](https://github.com/SlavicPotato/ied-dev/blob/master/ImmersiveEquipmentDisplays/IED/GearNodeID.h). 

Don't worry about the 'IED' nodes, they're not of any use here.. plus they were broken somewhere along 1.7 development, i've only noticed and fixed it yesterday

**Comment by SlavicPotato** [comment] 2023-08-13 08:25
[ImmersiveEquipmentDisplays.zip](https://github.com/SlavicPotato/ied-dev/files/12329064/ImmersiveEquipmentDisplays.zip)

**Comment by GiraPomba** [comment] 2023-08-13 14:04
Alright, got them working now. One thing I noticed is:
Two handed on right hand is sharing the same node, Greatswords and Battleaxes/Warhammers use the GearNodeID 5. 
Which is fine, since it's vanilla behavior and that could be changed in the UI.

But on the left hand however, they're using separate GearNodeIDs, Greatswords use 17, while Battleaxes/Warhammers use 18.

And the new gear node for Two-Handed Axe/Mace is "deactivated" for me here, maybe if I can enable it, then the weapons on the right hand will use separated IDs?
Pic: [https://imgur.com/AsnP0hi](https://imgur.com/AsnP0hi) 

But the conditions and displays are working fine now :D.

**Comment by SlavicPotato** [comment] 2023-08-13 14:09
Yeah that's fine, it doesn't matter whether a display is activated or lh item enabled in sds... I think you're looking to much into the visual side, what you should look for is a way to tell what **equip slot** (2h,1h,..) the weapon in question has.. What CGO does is change the equip slot on all 2h weapons between 1h and 2h as you toggle..

**Comment by GiraPomba** [comment] 2023-08-13 14:17
Oh, I also noticed that the left 2h weapons nodes are not loading correctly for my custom nodes (in this [mod](https://www.nexusmods.com/skyrimspecialedition/mods/92244)) but are loading fine for the slots in 00205_2HLeft.json

The "IEDTwoHandedBackHipLeft" is designed for 2h handed left weapons at back hip, it was working fine in previous versions. But now, assigning that node for the left weapons, makes them rotate (as if using a wrong node).

And if I use the "IEDTwoHandedBackHip", which is designed for the right hand weapons, for the left weapons, it makes them be displayed as if they're are a right hand weapon. Don't know if that makes sense.

If it's the inyended behavior I can adjust the .json files for this new version.

**Comment by GiraPomba** [comment] 2023-08-13 14:18
> P.S.: from what I can tell OAR doesn't have a condition to check this, I could add it in the plugin though..

OAR can detect 2h weapons equipped on the left hand with IsEquippedType.

**Comment by SlavicPotato** [comment] 2023-08-13 14:20
> OAR can detect 2h weapons equipped on the left hand with IsEquippedType.

Not what I was talking about, this determines whether it's a 1h or 2h weap:

![enb2023_8_6_11_20_17](https://github.com/SlavicPotato/ied-dev/assets/66538381/deef0d17-8483-4f03-acd2-932153f4619c)

**Comment by GiraPomba** [comment] 2023-08-13 14:22
Oh, yeah right, it doesn't have that. But I don't think it's necessary.

**Comment by SlavicPotato** [comment] 2023-08-13 14:23
Pretty sure it is, else there's no reliable way to tell 2h and 1h weapons apart when dealing with invasive modifications like what CGO does

**Comment by SlavicPotato** [comment] 2023-08-13 14:30
> The "IEDTwoHandedBackHipLeft" is designed for 2h handed left weapons at back hip, it was working fine in previous versions. But now, assigning that node for the left weapons, makes them rotate (as if using a wrong node).

> And if I use the "IEDTwoHandedBackHip", which is designed for the right hand weapons, for the left weapons, it makes them be displayed as if they're are a right hand weapon. Don't know if that makes sense.

If you're hinting at changes in how xfrm data is read, that would be fairly disastrous and would break even the included stuff (i'd have to update it, which I didn't except for reorganizing the files)... I'm reasonably sure you've got something else going on, maybe in your test environment?

**Comment by GiraPomba** [comment] 2023-08-13 14:34
If I set the Simple Dual Sheath ini like this:
```
[2HSword]
Flags=Player
SheathNode=WeaponBackLeft

[2HAxe]
Flags=Player
SheathNode=WeaponBackAxeMaceLeft
```
I will read from the 00205_2HLeft.json and it allows me to change the gear nodes with the UI. But assigning IEDTwoHandedBackHipLeft with the UI, makes the left hand weapons in the "wrong" position.

If I set the Simple Dual Sheath ini like this:
```
[2HSword]
Flags=Player
SheathNode=IEDTwoHandedBackHipLeft

[2HAxe]
Flags=Player
SheathNode=IEDTwoHandedBackHipLeft
```
It loads the weapons in the correct position (for those extra nodes), but I can't change them with the UI...

**Comment by SlavicPotato** [comment] 2023-08-13 14:44
Yeah that's normal since IED's placement moves WeaponBackLeft/WeaponBackAxeMaceLeft to "MOV IEDTwoHandedBackHipLeft", your MOV needs to be positioned in a way that's compatible with the back left nodes. We only added this ability yesterday (on your request lol), idk what you meant with "it was working fine in previous versions".. previously it was impossible to place WeaponBackLeft/WeaponBackAxeMaceLeft and it was never possible to place any custom nodes added via extensions.

> I could add it to the so called ['weapon nodes'](https://github.com/SlavicPotato/ied-dev/blob/master/ImmersiveEquipmentDisplays/IED/NodeOverrideData.cpp#L148-L500) (gear nodes is more accurate, the labeling is horrible in the code lol) list and assign a name/id to it, it would be picked up automatically if defined in extra nodes (there should already be WeaponBackLeft and WeaponBackAxeMaceLeft in the public package)

**Comment by SlavicPotato** [comment] 2023-08-13 14:51
Added new condition, ```IED_GearNodeEquippedPlacementHint```

> Same as IED_GearNodePlacementHint, except that it determines the gear node ID from an equipped weapon.

Found it pretty useful, can help reduce the complexity of your conditions

[Release MT Post 629 143.zip](https://github.com/SlavicPotato/ied-dev/files/12329747/Release.MT.Post.629.143.zip)

**Comment by SlavicPotato** [comment] 2023-08-13 15:27
Added ```IED_HasEquipSlot```

> Returns true if an item equipped in the target ref's hand has the specified equip slot configured.

[OpenAnimationReplacer-IEDConditionExtensions.zip](https://github.com/SlavicPotato/ied-dev/files/12329791/OpenAnimationReplacer-IEDConditionExtensions.zip)

**Comment by SlavicPotato** [comment] 2023-08-13 15:33
![Capture1](https://github.com/SlavicPotato/ied-dev/assets/66538381/300aaffa-8c00-4cca-8449-1b84d8ac94a6)
![Capture2](https://github.com/SlavicPotato/ied-dev/assets/66538381/4bed3bce-bb8d-4a36-96de-51f7e3c7454c)

**Comment by GiraPomba** [comment] 2023-08-13 15:46
> idk what you meant with "it was working fine in previous versions".
Oh, I meant with Simple Dual Sheath, using the node there in the ini. Okay then, I'll update the json files to be compatible with the new feature now. Thanks.

> Added new condition, `IED_GearNodeEquippedPlacementHint`
Nice, I was using isEquippedType, now I can delete that condition :D

> Added `IED_HasEquipSlot`
Neat, I think I can properly detect CGO now.

Now I need to think of a way to properly detect "Unrestricted placement" nodes. For example, default hint for Two-Handed is 1, default hint for One-Handed is 1.
If I set Two-Handed to One-Handed the ID will still be 1, but the One-Handed is at hip and not on back.
Maybe it's possible with IED_GearNodeParentName

Anyway, thanks for the new conditions and sorry for.the dumb questions lol.

**Comment by SlavicPotato** [comment] 2023-08-13 15:51
> If I set Two-Handed to One-Handed the ID will still be 1, but the One-Handed is at hip and not on back.

You could use IED_HasEquipSlot and assume that it's at the back when set to BothHands, but yeah IED_GearNodeParentName is more reliable since you can tell exactly where it is.. only that you may need several conditions to cover all the possible parent nodes

**Comment by SlavicPotato** [comment] 2023-08-13 16:53
Got a Q for you:

2hc_equip/unequip anims from xp32 (same as those included in your anim mod) seem to be missing female anims, I don't suppose there's a simple way to coax OAR into playing the male variants instead?

**Comment by GiraPomba** [comment] 2023-08-13 17:04
Are they separated? I never notice tbh, I thought all equip/unequip were on the "main" folder and not the "female/male default". I don't think it's possible for OAR to play animation from different projects right now. It's possible to copy-paste the animations. But that woulb probably mess the sleletons lol.

**Comment by SlavicPotato** [comment] 2023-08-13 17:12
Yeah they are, normally oar assigns a single hkx to both sexes, in this case they only play on male. They can't even be previewed on females. I barely know anything about this but I doubt there's two separate anims packed in the hkx, maybe they just need to be flagged to play for a particular sex..

**Comment by GiraPomba** [comment] 2023-08-13 17:18
Hmm, I see, I barely play as a female character.
I'll take a look and see what the game does for the vanilla 2hc animations and then try to replicate.
When I "made" those animations for my mod, I just copied and renamed the 1hm_equip/unequip animations, since it was a "sword at hip" animation for 2h weapons.

Theoretically, it should've worked. Maybe it's a different name for female chars?

**Comment by SlavicPotato** [comment] 2023-08-13 17:27
Copy pasted 2hc_* and 2hw_* into ```female``` subfolder and now it's picking them up heh

**Comment by GiraPomba** [comment] 2023-08-13 17:30
Nice catch :D, I'll add this to my mod when I update.

**Comment by GiraPomba** [comment] 2023-08-13 18:47
Btw, OAR has some nice conditions that IED could use. Like graph variable vars on the actors and Target function.

Target function could be used in a shader effect display to make weapons glow when near certain kind of enemies.

**Comment by SlavicPotato** [comment] 2023-08-13 19:07
I've pondered on implementing similar conditions in IED, the issue is performance.. These types of conditions need to be evaluated continously. IED has several different components with conditions each with potentially dozens (unlimited really) of entries, this wouldn't really scale well if each had to be evaluated on frame-by-frame basis.

The conditions that are implemented currently are actually only evaluated when:

 * events are recieved from the game (like equip, location change, etc..) either from the sinks already implemented in the game or though hooks installed by the plugin
 * by polling the [values](https://github.com/SlavicPotato/ied-dev/blob/master/ImmersiveEquipmentDisplays/IED/Controller/CachedActorData.cpp#L284-L298) that the conditions check like actor flags, sit state, combat state, and so on

This way it can completely avoid having to run each individual condition every frame which scales very well. There's still some cost when adding new conditions, but it's paid only when an eval triggers and even then it's minimal due to some heavy caching being done in the background. For example, before an eval runs the inventory data is built from the very slow linked list that the game stores it in and dumped into a sorted array for rapid random access. For example, if you make an effect and plaster it with getitemcount conditions, it will walk through that linked list each time which can cause huge slowdowns. In contrast, if you add a count condition somewhere in IED, it only needs to run a quick binary search through an array to find a particular form and read the count from it, everything is already cached.

**Comment by SlavicPotato** [comment] 2023-08-13 20:26
Added ```IED_PluginOption```, removed reverse axe hint (seems useless)

IED_PluginOption accepts keys 0 and 1 atm that read if frostfall idle/attack anims are enabled in settings (return values are 0 = disabled, 1 = enabled)

[Release MT Post 629 143.zip](https://github.com/SlavicPotato/ied-dev/files/12330336/Release.MT.Post.629.143.zip)

**Comment by GiraPomba** [comment] 2023-08-13 20:40
> I've pondered on implementing similar conditions in IED, the issue is performance..

Understandable. Thanks for the explanation.

> Added `IED_PluginOption`, removed reverse axe hint (seems useless)

I was using that hint lol. I even assigned it to a "reverse mace" node that I created.

**Comment by SlavicPotato** [comment] 2023-08-13 20:45
> I was using that hint lol. I even assigned it to a "reverse mace" node that I created.

Do you have an animation for it?

**Comment by GiraPomba** [comment] 2023-08-13 21:03
Yeah, actually I'm reusing the mace animation for the reverse axe and the axe animation for the reverse mace lol.
But I talked about expanding the animations with a friend of mine that's an animator, hopefully we can fill the gap soon.

**Comment by SlavicPotato** [comment] 2023-08-13 21:19
Alright, it's back 

[ImmersiveEquipmentDisplays.zip](https://github.com/SlavicPotato/ied-dev/files/12330444/ImmersiveEquipmentDisplays.zip)

**Comment by GiraPomba** [comment] 2023-08-13 21:27
Thanks.

**Comment by GiraPomba** [comment] 2023-08-13 22:46
I think I finished converting, conditions worked fine so far. Works well with Overrides and all.
Pretty cool.

[https://cdn.discordapp.com/attachments/1125787883748458558/1140415373473218662/Weapon_Styles_IED.7z](https://cdn.discordapp.com/attachments/1125787883748458558/1140415373473218662/Weapon_Styles_IED.7z)

The converted mod in case you're interested. I didn't mess with the "Unarmed/Staff on right hand" folders... Yet.
And didn't use the `IED_GearNodeParentName`. I'll consider it.

**Comment by SlavicPotato** [comment] 2023-08-14 09:15
Works great! Technically, the less you use that condition the better. It's for cases where there's no other choice.

**Comment by GiraPomba** [comment] 2023-08-14 11:07
Yeah, now I can truly have a "style randomizer".
I guess not many users would use the Unrestricted placement nodes, so it's not worth it to change the default ids or even use that condition.

**Comment by SlavicPotato** [comment] 2023-08-14 11:17
It wouldn't look right in almost every case.. Like if you move two-handed to sword or sword back, the position is totally off.. I suppose I could add hints to the default nodes too, but that would just mean more work for you since you'd have to rework conditions to accomodate for it (now you can just assume it's at its proper default position and let it fall through to whatever submod handles the weapon).. I don't think it's worth it imo

**Comment by SlavicPotato** [comment] 2023-08-14 11:23
Closing this for now, btw we can coninue this on discord so we don't blast repo watchers with notifications on here.. I'm in the nexus mods server atm, same username

**Closed by SlavicPotato** 2023-08-14 11:23 UTC
Labels: enhancement
